<a href="https://colab.research.google.com/github/yashwanthsurigi14/pythonbasics/blob/main/pandas_examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
3+5

8

In [ ]:
import pandas as pd

In [ ]:
x=pd.read_csv('Salaries.csv')

In [ ]:
x

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]

In [ ]:
x.head

<bound method NDFrame.head of          rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]>

In [ ]:
x.head()

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800

In [ ]:
x.tail()

         rank discipline  phd  service     sex  salary
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [ ]:
x.tail(10)

         rank discipline  phd  service     sex  salary
68   AsstProf          A    4        2  Female   77500
69       Prof          A   28        7  Female  116450
70   AsstProf          A    8        3  Female   78500
71  AssocProf          B   12        9  Female   71065
72       Prof          B   24       15  Female  161101
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [ ]:
x.shape

(78, 6)

In [ ]:
x.columns

Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')

In [ ]:
x.dtypes

rank          object
discipline    object
phd            int64
service        int64
sex           object
salary         int64
dtype: object

In [ ]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   rank        78 non-null     object
 1   discipline  78 non-null     object
 2   phd         78 non-null     int64
 3   service     78 non-null     int64
 4   sex         78 non-null     object
 5   salary      78 non-null     int64
dtypes: int64(3), object(3)
memory usage: 3.8+ KB

In [ ]:
x.isnull()

     rank  discipline    phd  service    sex  salary
0   False       False  False    False  False   False
1   False       False  False    False  False   False
2   False       False  False    False  False   False
3   False       False  False    False  False   False
4   False       False  False    False  False   False
..    ...         ...    ...      ...    ...     ...
73  False       False  False    False  False   False
74  False       False  False    False  False   False
75  False       False  False    False  False   False
76  False       False  False    False  False   False
77  False       False  False    False  False   False

[78 rows x 6 columns]

In [ ]:
pd.set_option('display.max_rows',None)

In [ ]:
x

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
5        Prof          A   20       20    Male  122400
6   AssocProf          A   20       17    Male   81285
7        Prof          A   18       18    Male  126300
8        Prof          A   29       19    Male   94350
9        Prof          A   51       51    Male   57800
10       Prof          B   39       33    Male  128250
11       Prof          B   23       23    Male  134778
12   AsstProf          B    1        0    Male   88000
13       Prof          B   35       33    Male  162200
14       Prof          B   25       19    Male  153750
15       Prof          B   17        3    Male  150480
16   AsstProf          B    8        3    Male   75044
17   AsstProf          B    4        0    Male   92000
18       Prof          A   19        7    Male  107300
19       Prof          A   29       27    Male  150500
20   AsstProf          B    4        4    Male   92000
21       Prof          A   33       30    Male  103106
22   AsstProf          A    4        2    Male   73000
23   AsstProf          A    2        0    Male   85000
24       Prof          A   30       23    Male   91100
25       Prof          B   35       31    Male   99418
26       Prof          A   38       19    Male  148750
27       Prof          A   45       43    Male  155865
28   AsstProf          B    7        2    Male   91300
29       Prof          B   21       20    Male  123683
30  AssocProf          B    9        7    Male  107008
31       Prof          B   22       21    Male  155750
32       Prof          A   27       19    Male  103275
33       Prof          B   18       18    Male  120000
34  AssocProf          B   12        8    Male  119800
35       Prof          B   28       23    Male  126933
36       Prof          B   45       45    Male  146856
37       Prof          A   20        8    Male  102000
38   AsstProf          B    4        3    Male   91000
39       Prof          B   18       18  Female  129000
40       Prof          A   39       36  Female  137000
41  AssocProf          A   13        8  Female   74830
42   AsstProf          B    4        2  Female   80225
43   AsstProf          B    5        0  Female   77000
44       Prof          B   23       19  Female  151768
45       Prof          B   25       25  Female  140096
46   AsstProf          B   11        3  Female   74692
47  AssocProf          B   11       11  Female  103613
48       Prof          B   17       17  Female  111512
49       Prof          B   17       18  Female  122960
50   AsstProf          B   10        5  Female   97032
51       Prof          B   20       14  Female  127512
52       Prof          A   12        0  Female  105000
53   AsstProf          A    5        3  Female   73500
54  AssocProf          A   25       22  Female   62884
55   AsstProf          A    2        0  Female   72500
56  AssocProf          A   10        8  Female   77500
57   AsstProf          A    3        1  Female   72500
58       Prof          B   36       26  Female  144651
59  AssocProf          B   12       10  Female  103994
60   AsstProf          B    3        3  Female   92000
61  AssocProf          B   13       10  Female  103750
62  AssocProf          B   14        7  Female  109650
63       Prof          A   29       27  Female   91000
64  AssocProf          A   26       24  Female   73300
65       Prof          A   36       19  Female  117555
66   AsstProf          A    7        6  Female   63100
67       Prof          A   17       11  Female   90450
68   AsstProf          A    4        2  Female   77500
69       Prof          A   28        7  Female  116450
70   AsstProf          A    8        3  Female   78500
71  AssocProf          B   12        9  Female   71065
72       Prof          B   24       15  Female  161101
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [ ]:
x.isnull().sum()

rank          0
discipline    0
phd           0
service       0
sex           0
salary        0
dtype: int64

In [ ]:
x.describe()

             phd    service         salary
count  78.000000  78.000000      78.000000
mean   19.705128  15.051282  108023.782051
std    12.498425  12.139768   28293.661022
min     1.000000   0.000000   57800.000000
25%    10.250000   5.250000   88612.500000
50%    18.500000  14.500000  104671.000000
75%    27.750000  20.750000  126774.750000
max    56.000000  51.000000  186960.000000

In [ ]:
x['salary']

0     186960
1      93000
2     110515
3     131205
4     104800
5     122400
6      81285
7     126300
8      94350
9      57800
10    128250
11    134778
12     88000
13    162200
14    153750
15    150480
16     75044
17     92000
18    107300
19    150500
20     92000
21    103106
22     73000
23     85000
24     91100
25     99418
26    148750
27    155865
28     91300
29    123683
30    107008
31    155750
32    103275
33    120000
34    119800
35    126933
36    146856
37    102000
38     91000
39    129000
40    137000
41     74830
42     80225
43     77000
44    151768
45    140096
46     74692
47    103613
48    111512
49    122960
50     97032
51    127512
52    105000
53     73500
54     62884
55     72500
56     77500
57     72500
58    144651
59    103994
60     92000
61    103750
62    109650
63     91000
64     73300
65    117555
66     63100
67     90450
68     77500
69    116450
70     78500
71     71065
72    161101
73    105450
74    104542
75    124312
76    109954
77    109646
Name: salary, dtype: int64

In [ ]:
x['salary'].mean()

108023.78205128205

In [ ]:
x['salary'].median()

104671.0

In [ ]:
x['salary'].mode()

0    92000
Name: salary, dtype: int64

In [ ]:
x['salary'].var()

800531254.0427907

In [ ]:
x['salary'].std()

28293.66102226417

In [ ]:
x['salary'].kurt()

-0.4017126758820546

In [ ]:
x[['salary','service']].mean()

salary     108023.782051
service        15.051282
dtype: float64

In [ ]:
x.mean()

<ipython-input-34-6f9184126d05>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  x.mean()

phd            19.705128
service        15.051282
salary     108023.782051
dtype: float64

In [ ]:
import warnings
warnings.filterwarnings('ignore')
x.mean()

phd            19.705128
service        15.051282
salary     108023.782051
dtype: float64

In [ ]:
x['salary']>120000

0      True
1     False
2     False
3      True
4     False
5      True
6     False
7      True
8     False
9     False
10     True
11     True
12    False
13     True
14     True
15     True
16    False
17    False
18    False
19     True
20    False
21    False
22    False
23    False
24    False
25    False
26     True
27     True
28    False
29     True
30    False
31     True
32    False
33    False
34    False
35     True
36     True
37    False
38    False
39     True
40     True
41    False
42    False
43    False
44     True
45     True
46    False
47    False
48    False
49     True
50    False
51     True
52    False
53    False
54    False
55    False
56    False
57    False
58     True
59    False
60    False
61    False
62    False
63    False
64    False
65    False
66    False
67    False
68    False
69    False
70    False
71    False
72     True
73    False
74    False
75     True
76    False
77    False
Name: salary, dtype: bool

In [ ]:
x[x['salary']>120000]

    rank discipline  phd  service     sex  salary
0   Prof          B   56       49    Male  186960
3   Prof          A   40       31    Male  131205
5   Prof          A   20       20    Male  122400
7   Prof          A   18       18    Male  126300
10  Prof          B   39       33    Male  128250
11  Prof          B   23       23    Male  134778
13  Prof          B   35       33    Male  162200
14  Prof          B   25       19    Male  153750
15  Prof          B   17        3    Male  150480
19  Prof          A   29       27    Male  150500
26  Prof          A   38       19    Male  148750
27  Prof          A   45       43    Male  155865
29  Prof          B   21       20    Male  123683
31  Prof          B   22       21    Male  155750
35  Prof          B   28       23    Male  126933
36  Prof          B   45       45    Male  146856
39  Prof          B   18       18  Female  129000
40  Prof          A   39       36  Female  137000
44  Prof          B   23       19  Female  151768
45  Prof          B   25       25  Female  140096
49  Prof          B   17       18  Female  122960
51  Prof          B   20       14  Female  127512
58  Prof          B   36       26  Female  144651
72  Prof          B   24       15  Female  161101
75  Prof          B   17       17  Female  124312

In [ ]:
type(x)

pandas.core.frame.DataFrame

In [ ]:
  x.max()

rank            Prof
discipline         B
phd               56
service           51
sex             Male
salary        186960
dtype: object

In [ ]:
x['rank'].value_counts

<bound method IndexOpsMixin.value_counts of 0          Prof
1          Prof
2          Prof
3          Prof
4          Prof
5          Prof
6     AssocProf
7          Prof
8          Prof
9          Prof
10         Prof
11         Prof
12     AsstProf
13         Prof
14         Prof
15         Prof
16     AsstProf
17     AsstProf
18         Prof
19         Prof
20     AsstProf
21         Prof
22     AsstProf
23     AsstProf
24         Prof
25         Prof
26         Prof
27         Prof
28     AsstProf
29         Prof
30    AssocProf
31         Prof
32         Prof
33         Prof
34    AssocProf
35         Prof
36         Prof
37         Prof
38     AsstProf
39         Prof
40         Prof
41    AssocProf
42     AsstProf
43     AsstProf
44         Prof
45         Prof
46     AsstProf
47    AssocProf
48         Prof
49         Prof
50     AsstProf
51         Prof
52         Prof
53     AsstProf
54    AssocProf
55     AsstProf
56    AssocProf
57     AsstProf
58         Prof
59    AssocProf
60     AsstProf
61    AssocProf
62    AssocProf
63         Prof
64    AssocProf
65         Prof
66     AsstProf
67         Prof
68     AsstProf
69         Prof
70     AsstProf
71    AssocProf
72         Prof
73         Prof
74    AssocProf
75         Prof
76         Prof
77         Prof
Name: rank, dtype: object>

In [ ]:
x['rank'].value_counts()

Prof         46
AsstProf     19
AssocProf    13
Name: rank, dtype: int64

In [ ]:
x.max(

)

rank            Prof
discipline         B
phd               56
service           51
sex             Male
salary        186960
dtype: object

In [ ]:
x['service'].value_counts()

3     7
19    6
0     6
18    5
2     4
7     4
8     4
6     3
20    3
10    3
17    3
23    3
14    2
11    2
15    2
27    2
31    2
33    2
30    1
51    1
9     1
24    1
26    1
1     1
22    1
5     1
4     1
25    1
36    1
45    1
21    1
43    1
49    1
Name: service, dtype: int64